In [1]:
help('keywords')


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



In [2]:
import keyword
keyword.iskeyword('with')

True

In [3]:
import keyword
keyword.iskeyword('global')

True

In [4]:
'trail'.isidentifier()

True

In [5]:
'trail.d@'.isidentifier()

False

In [6]:
t=327

In [7]:
v=3.4

In [8]:
id(v)

2989096637744

In [9]:
print(print('hello world'))

hello world
None


In [10]:
# input and Output Statement

In [12]:
num=input("enter a number")

enter a number 5


In [13]:
print(v,'is type',type(v))

3.4 is type <class 'float'>


In [14]:
str='hello Biswa'

In [15]:
# string opertaion

In [16]:
str[3]

'l'

In [17]:
str[0:5]

'hello'

In [18]:
str[0:7:2]

'hloB'

In [19]:
str[6:11]

'Biswa'

In [20]:
str[-4]

'i'

In [21]:
str[::-1]

'awsiB olleh'

In [22]:
str*3

'hello Biswahello Biswahello Biswa'

In [23]:
str.capitalize()

'Hello biswa'

In [24]:
str.upper()

'HELLO BISWA'

In [25]:
str.swapcase()

'HELLO bISWA'

In [26]:
str.split()

['hello', 'Biswa']

In [26]:
h='I am Biswajit'

In [27]:
h.split()

['I', 'am', 'Biswajit']

In [28]:
h.count('a')

2

In [29]:
s='   Nothing is impossible  '

In [30]:
s.rstrip()

'   Nothing is impossible'

In [31]:
s.strip()

'Nothing is impossible'

# List

In [32]:
l=['BISWA',5,'hello',3.4]

In [33]:
l[0:3]

['BISWA', 5, 'hello']

In [34]:
l[:3]

['BISWA', 5, 'hello']

In [35]:
l*2

['BISWA', 5, 'hello', 3.4, 'BISWA', 5, 'hello', 3.4]

In [36]:
l.append('Mango')

In [37]:
print(l)

['BISWA', 5, 'hello', 3.4, 'Mango']


In [39]:
l.insert(2,'Aman')

In [40]:
print(l)

['BISWA', 5, 'Aman', 'Aman', 'hello', 3.4, 'Mango']


In [41]:
l.count(5)

1

In [42]:
l.remove('hello')

In [43]:
print(l)

['BISWA', 5, 'Aman', 'Aman', 3.4, 'Mango']


In [44]:
l.reverse()

In [45]:
print(l)

['Mango', 3.4, 'Aman', 'Aman', 5, 'BISWA']


In [7]:
list=[4,5,6,7,8,9]

In [8]:
list.reverse()

In [9]:
print(list)

[9, 8, 7, 6, 5, 4]


In [13]:
list.sort()
print(list)

[4, 5, 6, 7, 8, 9]


In [14]:
list.pop(3)
print(list)

[4, 5, 6, 8, 9]


# Tuple

In [3]:
tup=(2,'ram',3.4)

In [4]:
tup[2]

3.4

In [5]:
tup1=(4,5,8,'bapun')

In [6]:
tup+tup1

(2, 'ram', 3.4, 4, 5, 8, 'bapun')

In [19]:
tup.count(5)

0

# Dt - 30/05/25

# Dictionary

In [1]:
dict={'name':'Bisaw','Roll':47,'Branch':'CSE'}

In [2]:
dict['name']

'Bisaw'

In [3]:
dict.items()

dict_items([('name', 'Bisaw'), ('Roll', 47), ('Branch', 'CSE')])

In [5]:
dict={'Roll':40}
dict.update(dict)

# Set

In [10]:
a={1,2,3,4,5}

In [11]:
a.add(6)

In [12]:
print(a)

{1, 2, 3, 4, 5, 6}


In [20]:
b={9,10}
a.union(b)

{1, 2, 3, 4, 5, 6, 9, 10}

In [21]:
a.intersection(b)

set()

In [22]:
a.difference(b)

{1, 2, 3, 4, 5, 6}

In [23]:
b.issubset(a)

False

In [24]:
a.isdisjoint(b)

True

In [25]:
a.remove(1)

In [26]:
a

{2, 3, 4, 5, 6}

In [28]:
b.add(3)

In [29]:
a.symmetric_difference(b)

{2, 4, 5, 6, 9, 10}

# Arithmetic Opertors

In [31]:
x=30
y=80

In [32]:
print(x+y)


110


In [33]:
print(x-y)

-50


In [34]:
print(x/y)

0.375


In [35]:
print(x*y)

2400


In [36]:
print(x%y)

30


In [37]:
# floor division
print(x//y)

0


# Comparsion operators

In [41]:
print(x<y)
print(x>y)
print(x!=y)
print(x==y)

True
False
True
False


# Logical operators

In [44]:
x=True
y=False
print('x and y is',x and y)
print('x or y is',x or y)

x and y is False
x or y is True


In [45]:
a=5
b=5
print(x is y)

False


In [46]:
print(x is not y)

True


# Decision making 

In [47]:
# if Statement

In [50]:
n=int(input('Enter a number'))
if n>0:
    print(n,'is positive')

Enter a number 3


3 is positive


In [51]:
# if else statement

In [52]:
n=int(input('Enter a number'))
if n>0:
    print(n,'is positive')
else:
    print(n,'is negative')

Enter a number -3


-3 is negative


In [53]:
# if elif statement

In [54]:
n=int(input('Enter a number'))
if n>0:
    print(n,'is positive')
elif n==0:
    print(n,'is Zero')
else:
    print(n,'is negative')

Enter a number 0


0 is Zero


In [55]:
n=int(input('Enter a number'))
if n%2==0:
    print(n,'is even')
else:
    print(n,'is Odd')

Enter a number 60


60 is even


In [56]:
for i in range (11):
    print (i)
    

0
1
2
3
4
5
6
7
8
9
10


In [57]:
for i in range (0,10,2):
    print(i,end=" ")

0 2 4 6 8 

In [58]:
for i in range(9,5,-1):
    print(i,end="😒")

9😒8😒7😒6😒

In [61]:
n=int(input("Enter The  number:"))
s=0
for i in range(0,n+1):
    s+=i
print(s)

Enter The  number: 5


15


In [62]:
for i in range (1,6):
    for j in range(i):
        print(i,end="😊")
    print()

1😊
2😊2😊
3😊3😊3😊
4😊4😊4😊4😊
5😊5😊5😊5😊5😊


In [65]:
for i in range (1,6):
    for j in range(i):
        print('*',end=" ")
    print()

* 
* * 
* * * 
* * * * 
* * * * * 


In [68]:
for i in range (1,6):
    for j in range(i):
        print('*',end=" ")
    print()
for i in range (6,0,-1):
    for j in range(i):
        print('*',end=" ")
    print()

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [69]:
# while loop

In [70]:
i=1
while i<5:
    print(i)
    i+=1

1
2
3
4


In [72]:
# sum of n numbers
n= int(input("Enter a number:"))
i=1
sum=0
while i<=n:
    sum+=i
    i+=1
print(sum)

Enter a number: 5


15


In [74]:
# while loop with else
count=0
while count<3:
    print("inside loop")
    count+=1
else:
    print("out of the loop")
    

inside loop
inside loop
inside loop
out of the loop


In [1]:
n=int(input("Enter a number:"))
i=1
while i<=10:
    print(f"{n} x {i} =",n*i)
    i+=1

Enter a number: 5


5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


# Dt- 31/05/25

In [13]:
for i in 'python':
    if i=='h':
        break
    print(i)

p
y
t


In [16]:
for i in 'python':
    if i=='h':
        continue
    print(i)

p
y
t
o
n


In [17]:
for i in 'python':
    if i=='h':
        pass
    print(i)

p
y
t
h
o
n


In [18]:
if 5>9:
    pass

In [19]:
# Funtion

In [1]:
max(45,21,3,45)

45

In [10]:
min(45,21,3,45,2)

2

In [7]:
def greet():
    print("Hello")

In [8]:
greet()

Hello


In [9]:
def greet(name):
    print("Hello",name)

In [13]:
greet('Biswa')

Hello Biswa


In [11]:
def add(num1,num2):
    return num1+num2

In [12]:
add(5,6)

11

In [1]:
def fun(*abc):
    return sum(abc)

In [2]:
fun(23,43,56,67,88,32)

309

In [4]:
def isEven(n):
    if n%2==0:
        return 'Even'
    else:
        return 'Not Even'

In [5]:
isEven(8)

'Even'

In [10]:
# Write a funtion to calculate the sum of all integers upto given number
def add(n):
    s=0
    for i in range(1,n+1):
        s+=i
    return s


In [11]:
add(5)

15

In [12]:
# OOPS

In [17]:
class Apple:
    color='Red'
    taste='sweet'
    def fun(abc):
        return 'An Apple a day keeps doctor away🍎'

In [18]:
obj=Apple()

In [19]:
obj.color

'Red'

In [20]:
obj.taste

'sweet'

In [28]:
class Apple:
    color='Red'
    taste='sweet'
    amount=100
    def price(abc,qty):
        return abc.amount*qty

In [29]:
o=Apple()

In [30]:
o.amount

100

In [31]:
o.price(2)

200

In [37]:
class Bird:
    name='parrot'
    age=2
    color='green'
    weight=50
    def eat(self,amt):
        return self.weight+amt

In [38]:
b=Bird()

In [39]:
b.eat(20)

70

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])

In [2]:
a

array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
s=np.array({1,23,4,45,465,74,757,65,4,46,56,3,53,7})

In [5]:
s

array({65, 1, 3, 4, 7, 74, 45, 46, 465, 757, 53, 23, 56}, dtype=object)

In [7]:
d=np.array({'a':2,'b':4})

In [8]:
d

array({'a': 2, 'b': 4}, dtype=object)

# Dt- 02/06/25

In [3]:
import numpy as np
a=np.array([(2,3,4),(5,6,7),(8,9,10)])
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
a.shape

(3, 3)

In [5]:
a.size

9

In [6]:
a.ndim

2

In [7]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
c=np.zeros((4,4),dtype=int)

In [11]:
c

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [15]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.random.rand(3,4)

array([[0.57908873, 0.36573564, 0.41045547, 0.14759784],
       [0.79623555, 0.43814054, 0.1893319 , 0.30868124],
       [0.43147778, 0.07518698, 0.81874049, 0.61986475]])

In [18]:
np.random.rand(3,4)*100

array([[10.78785563, 72.91513758, 59.19314827, 84.30964268],
       [27.03350493, 53.00165684, 56.45647672, 44.86060865],
       [91.43150476, 32.7542948 , 48.86333788, 85.17566236]])

In [19]:
np.random.randint(1,10,(3,3))

array([[4, 7, 2],
       [4, 9, 1],
       [2, 6, 8]])

In [20]:
# Mathematical opration
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
sum=np.add(a,b)

In [21]:
sum

array([ 6,  8, 10, 12])

In [22]:
np.subtract(a,b)

array([-4, -4, -4, -4])

In [23]:
np.multiply(a,b)

array([ 5, 12, 21, 32])

In [24]:
np.divide(a,b)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [25]:
c=np.array([(2,3,4),(5,6,7),(8,9,10)])
d=np.array([(4,3,1),(3,2,4),(4,3,1)])
np.add(c,d)

array([[ 6,  6,  5],
       [ 8,  8, 11],
       [12, 12, 11]])

In [26]:
np.subtract(c,d)

array([[-2,  0,  3],
       [ 2,  4,  3],
       [ 4,  6,  9]])

In [27]:
np.multiply(c,d)

array([[ 8,  9,  4],
       [15, 12, 28],
       [32, 27, 10]])

In [28]:
np.divide(c,d)

array([[ 0.5       ,  1.        ,  4.        ],
       [ 1.66666667,  3.        ,  1.75      ],
       [ 2.        ,  3.        , 10.        ]])

In [29]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.mod(a,b)

array([1, 2, 3, 4])

In [30]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [31]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [32]:
np.tan(b)

array([-3.38051501, -0.29100619,  0.87144798, -6.79971146])

In [33]:
np.cos(b)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

In [34]:
np.power(a,2)

array([ 1,  4,  9, 16], dtype=int32)

In [35]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [36]:
np.max(a)

4

In [37]:
np.min(a)

1

In [38]:
np.mean(a)

2.5

In [39]:
np.median(b)

6.5

In [40]:
np.var(a)

1.25

In [41]:
np.mean(c,axis=1)

array([3., 6., 9.])

In [42]:
np.add(a,2)

array([3, 4, 5, 6])

In [43]:
np.subtract(a,1)

array([0, 1, 2, 3])

In [44]:
# Dot product
a

array([1, 2, 3, 4])

In [45]:
b

array([5, 6, 7, 8])

In [46]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [47]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [48]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [49]:
d=np.array([0,1,1,1,3,3,4,5,6,6,7])
np.unique(d)

array([0, 1, 3, 4, 5, 6, 7])

In [50]:
np.repeat(d,2)

array([0, 0, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7])

In [51]:
# indexing
a

array([[1, 2],
       [3, 4]])

In [52]:
a=np.array([1,2,3,4])

In [57]:
c=np.array([(2,3,4),(5,6,7),(8,9,10)])
d=np.array([(4,3,1),(3,2,4),(4,3,1)])

In [58]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [59]:
d

array([[4, 3, 1],
       [3, 2, 4],
       [4, 3, 1]])

In [54]:
c[2,2]

10

In [55]:
a=np.array([(1,2,4,3),(1,4,5,6),(3,7,8,9)])
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [56]:
a[2:4,1:4:2]

array([[7, 9]])

# Dt - 03/06/25

In [60]:
c[:,1:3]

array([[ 3,  4],
       [ 6,  7],
       [ 9, 10]])

In [62]:
a=np.array([(21,23,43,21),(23,44,54,21),(21,43,23,65),(43,42,32,12)])

In [63]:
a[2:4,1:4:2]

array([[43, 65],
       [42, 12]])

In [64]:
a[:,2:4]

array([[43, 21],
       [54, 21],
       [23, 65],
       [32, 12]])

In [65]:
a[1:3,:]

array([[23, 44, 54, 21],
       [21, 43, 23, 65]])

In [66]:
a[:,:]

array([[21, 23, 43, 21],
       [23, 44, 54, 21],
       [21, 43, 23, 65],
       [43, 42, 32, 12]])

In [67]:
mat1=np.random.randint(0,100,(2,4))
mat2=np.random.randint(0,100,(2,4))

In [68]:
mat1

array([[10, 91, 69, 12],
       [26, 71, 61, 27]])

In [69]:
mat2

array([[30, 37, 52, 16],
       [45,  6, 18, 17]])

In [70]:
np.concatenate((mat1,mat2))

array([[10, 91, 69, 12],
       [26, 71, 61, 27],
       [30, 37, 52, 16],
       [45,  6, 18, 17]])

In [71]:
np.concatenate((mat1,mat2),axis=1)

array([[10, 91, 69, 12, 30, 37, 52, 16],
       [26, 71, 61, 27, 45,  6, 18, 17]])

In [72]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [73]:
s=np.append(c,[3,4,2])

In [74]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [84]:
s

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10,  3,  4,  2])

In [76]:
s1=np.append(c,[[2,3,4]],axis=0)

In [77]:
s1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [ 2,  3,  4]])

In [85]:
s2=np.append(c,[[2,5,0],[2,3,4],[6,3,2]],axis=1)

In [86]:
s2

array([[ 2,  3,  4,  2,  5,  0],
       [ 5,  6,  7,  2,  3,  4],
       [ 8,  9, 10,  6,  3,  2]])

In [87]:
a=np.array([[2,3],[4,5],[2,5]])
d=np.insert(a,1,[11])

In [88]:
d

array([ 2, 11,  3,  4,  5,  2,  5])

In [90]:
b=np.insert(a,1,[11],axis=0)

In [91]:
b

array([[ 2,  3],
       [11, 11],
       [ 4,  5],
       [ 2,  5]])

In [92]:
b=np.insert(a,1,[11],axis=1)

In [93]:
b

array([[ 2, 11,  3],
       [ 4, 11,  5],
       [ 2, 11,  5]])

In [94]:
b=np.insert(a,1,[32,24,56],axis=1)

In [95]:
b

array([[ 2, 32,  3],
       [ 4, 24,  5],
       [ 2, 56,  5]])

In [97]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [98]:
np.split(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [99]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [100]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [101]:
a=np.array([[1,2],[3,4]])
b=np.array([[3,2],[4,3]])

In [102]:
np.stack((a,b),0)

array([[[1, 2],
        [3, 4]],

       [[3, 2],
        [4, 3]]])

In [103]:
np.hstack((a,b))

array([[1, 2, 3, 2],
       [3, 4, 4, 3]])

In [104]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [3, 2],
       [4, 3]])

In [105]:
a=np.arange(12).reshape(3,4)

In [106]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
a2=np.delete(a,5)

In [109]:
a2

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])